### ISSUE TITLE
`.get()` is deprecated

### ISSUE THREAD

**Issue by dmitrif** [alexkuz/redux-pagan#7]
It seems that with 0.2.0 `.get()` is deprecated in favour of getLand. Could you please update the documentation in accordance to intended usage?

Thank you!

**Comment by dmitrif** [comment]
In particular this line:

> i18n.get(...path) is a special method that safely obtains strings from lang data. If no strings were found on stated path, last key is returned. This method's calling is chainable:

**Comment by alexkuz** [comment]
Well, that's a way to remind me :) Fixed that, thanks for the issue!
