### ISSUE TITLE
Force-recache JSON files?

### ISSUE THREAD

**Issue by NeXTs** [alexkuz/redux-pagan#8]
Hey Alex

Do you have any idea how to trigger force-recache of localization JSON files?
Let's say my localization files were updated and I want to trigger users browser to force-reload them.

```
function getLangData(locale) {
  // here we use promise-loader to load lang data by demand
  return require('promise?global,[name].i18n!json!./i18n/' + locale + '.i18n.json');
}
```

I was thinking about using that ?v=2 trick inside this require but it didn't work

**Comment by alexkuz** [comment]
Have you tried calling `loadLang` again? It should do the trick.

**Comment by NeXTs** [comment]
Попробовал, на локалхосте работает. Но сдается мне что на продакшне со всем этим кешированием такое не сработает. У меня сейчас нет возможности проверить изменения на продакшне, но я помню как это происходило раньше. После обновления билда (с обновленными локалями) я обновлял страницу, это не помогало. Я переключал разные языки (тригеррился loadLang), это не помогало. Приходилось вручную открывать json файл в новом табе и делать force recache конкретно этому файлу, вот только после этого файл обновлялся. Вот поэтому я и решил попробовать использовать способ с изменением хеша ?v=2 для принудительной перегрузки файла браузером.

**Comment by alexkuz** [comment]
Ну, кеширование браузера, конечно, к `redux-pagan` не относится, он просто получает промис, возвращающий данные. Так что да, `?v=2` (либо сброс кеширования сервером) в данном случае потребуется, но и вызов `loadLang` тоже.

**Comment by NeXTs** [comment]
вот только не влазит оно никак в этот синтаксис :(

если использовать так
`return require('promise?global,[name].i18n!i18n/' + locale + '.i18n.json?v=2');`
то ругается на
`Uncaught (in promise) Error: Cannot find module "promise?global,[name].i18n!i18n"`

 а если так
`return require('promise?global,[name].i18n?v=2!i18n/' + locale + '.i18n.json');`
то ничего и не меняется

куда стучаться с таким вопросом вообще? в promise-loader, bundle-loader, webpack репу..?

**Comment by alexkuz** [comment]
Ах, да :) В этом случае проще самому делать запрос, а не полагаться на вебпак:
```js
function getLangData(locale) {
  return fetch('path/to/file/i18n/' + locale + '.i18n.json').then(res => res.json());
}
```
(вообще, это стоит сделать дефолтным примером в README)

**Comment by NeXTs** [comment]
Этот вариант для меня тоже не сработал на пару с webpack-dev-server т.к. одному богу известно какие там пути подставлять нужно

а вот что мне помогло так это указать в конфиге вебпака output.chunkFilename, и работает оно с изначальным примером из доки с promise-loader

```
output: {
  ...
  chunkFilename: [name].chunk.js?v=[hash]
}
```
