### ISSUE TITLE
React 16 support?

### ISSUE THREAD

**Issue by NeXTs** [alexkuz/redux-pagan#9]
Hello
Are you planning to add react 16 support?

**Comment by NeXTs** [comment]
React 16 does not support functions in render as React 15 did.

"Warning: Functions are not valid as a React child. This may happen if you return a Component instead of <Component /> from render. Or maybe you meant to call this function rather than return it."

It works fine if call it as function manually, but maybe you have an idea how to fix it without adding function calls everywhere?
```
lang("key")()
```

**Comment by alexkuz** [comment]
@NeXTs sorry I've missed this issue - you have to use `.toString()` or `.s` (I'll fix the README)
